### ISSUE TITLE
Fix pls

### ISSUE THREAD

**Issue by 5k-omar** [tuberboy/recaptcha-solver-or-bypasser#1]
Deprecated: Creation of dynamic property mcCS\captcha\solveCAPTCHA::$ua is deprecated in C:\recaptcha-solver-or-bypasser-main\Captcha\solveCAPTCHA.php on line 39

in `preg_match('/k=(.+?)\&/', $anchor_url, $key); `

**Comment by tuberboy** [comment]
> Deprecated: Creation of dynamic property mcCS\captcha\solveCAPTCHA::$ua is deprecated in C:\recaptcha-solver-or-bypasser-main\Captcha\solveCAPTCHA.php on line 39
> 
> in `preg_match('/k=(.+?)\&/', $anchor_url, $key); `

Your anchor url is incorrect, double check and use correct anchor url.

Search for "anchor" in the network tab while the site is loading to obtain the url.

Anchor url should look like:
`https://www.google.com/recaptcha/api2/anchor?ar=1&k=...&...`

Use `php7.4`, Deprecated warning will not show.
